### ISSUE TITLE
GroupElem vs GroupElement

### ISSUE THREAD

**Issue by albinahlback** [kalmarek/GroupsCore.jl#1]
Personally, I think that GroupElem should be used since AA uses that syntax.

**Comment by kalmarek** [comment]
sure, that's one replace away ;)

On the other hand:
```julia
julia> AbstractAlgebra.RingElement
RingElement (alias for Union{RingElem, AbstractFloat, Integer, Rational})

```
and this is the type that should be used in general functions. So...

Anyway, I'd postpone the discussion about names and whether to use run-together vs underscore, verb-adj vs. adj-verb etc. until the semantics of the interface are decided.

**Comment by albinahlback** [comment]
Yes! I think of _Element of being a union of types.

**Comment by kalmarek** [comment]
Yes, but what would you union it with? (again, I'm not against, just looking for an actual reason)

**Comment by albinahlback** [comment]
Hmm, good point.
