### ISSUE TITLE
Information in docstrings to README

### ISSUE THREAD

**Issue by albinahlback** [kalmarek/GroupsCore.jl#12]
Some comments, like
```
@doc Markdown.doc"""
     order(...)
...

Only arbitrary size integers are required to return mathematically correct answer.
"""
```
I think is a better fit for the readme, alternatively the documentation.

What do you think about this?

**Comment by albinahlback** [comment]
Oh, it already was. But anyway, do you think it is useful to have it in the docstring?

**Comment by kalmarek** [comment]
yes!
