### ISSUE TITLE
Ideas: Non-finitely presented groups

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/GroupsCore.jl#19]
What do we need to provide a useful interface for those? @thofma

**Comment by thofma** [comment]
Useful as in "one should be able to write generic functions assuming the interface is implemented" or useful as in "a user should expect these functions to exist"?

**Comment by kalmarek** [comment]
you choose ;) both are fine with me.

**Comment by thofma** [comment]
I think everything except the iteration is fine.

**Comment by kalmarek** [comment]
how do you use such groups? do they come with (an infinite) generator `gens` ?
If now, we could simply hide iteration requirement behind `hasgens` predicate.

**Comment by thofma** [comment]
The ones I am interested in come with an explicit model, like $\GL(n, \Q)$. So one can write down elements or ask for random elements.

**Comment by kalmarek** [comment]
ok, so would requiring iteration for fp groups suit you?
