### ISSUE TITLE
Less abbreviations

### ISSUE THREAD

**Issue by thofma** [kalmarek/GroupsCore.jl#20]
We are trying to steer away from (domain-specific) abbreviations in Oscar (see the recent deprecations of `lm`, `lc` and `coeff*`). I think it would be good idea to take this also into account here right from the beginning. So instead of `comm` it would be `commutator` or `conjugate` instead of `conj`.

**Comment by blegat** [comment]
I agree with `comm` vs `commutator`. For the conjugate, it's best to be consistent with Julia Base and use `Base.conj`

**Comment by thofma** [comment]
I think `Base.conj` is a different concept then group conjugation. This would clash for anything to do with finite fields, where conjugation in the field theoretic sense of `Base.conj` usually refers to the Frobenius map.

**Comment by kalmarek** [comment]
so what will happen to `mul!`, `div!` etc? will it be kept as is, or are we heading for `multiply!`?

Is there a chance of collision in the finite fields context? It was decided that these are not groups after all (or do I remember it wrongly?)
