### ISSUE TITLE
Use GroupsCore conformance tests for Oscar groups -- first attempt

### ISSUE THREAD

**Issue by ThomasBreuer** [kalmarek/GroupsCore.jl#24]
As a first step in using the GroupsCore conformance tests for Oscar groups, I have tried the following in a Julia session.
```
using Oscar
using GroupsCore
using Test
include(pathof(GroupsCore) * "/../../test/conformance_test.jl");
G = symmetric_group(3);
test_Group_interface(G)
```
(It may be necessary to change the AbstractAlgebra version in GroupsCore's dependencies, depending on the Oscar version.)

I get the one failure and two kinds of errors.

- The failure happens in the test `order(G) isa Integer`; this is due to the fact that the unary `Oscar.order` returns an `fmpz`, which is not an integer. (Well, it is not a `Base.Integer`. Note that `Oscar.Integer` is set to `fmpz`, thus one has to be careful about the context of the code.)
Thus the type check itself is perhaps not what one wants; one could add the desired type as an argument to `test_Group_interface`. I do not see how to fix the failure on the Oscar side.

- The first error happens in the statement `order(Int16, G)`, I get `MethodError: order(::Type{Int16}, ::PermGroup) is ambiguous`.
This is due to the fact that Julia regards the `order` methods in `GroupsCore.jl/src/groups.jl` and in `Oscar.jl/src/Groups/GAPGroups.jl` as "concurrent". Note that the GroupsCore installation is for `order(::Type{<:Integer}, G::Group)` and the Oscar installation is for `order(::Type{T}, x::Union{GAPGroupElem, GAPGroup}) where T`. So we could fix the problem in Oscar by installing the method also for `order(::Type{T}, x::GAPGroup) where T<:Base.Integer`, but this looks ugly; is there a better way?

- The other errors happen in calls of the form `GroupsCore.pseudo_rand(G)`, which delegate to `rand(Random.default_rng(), G)`. However, the unary `rand` method for a GAP group in Oscar delegates to a GAP function that uses GAP's random number generators. Is it really necessary to support `Random.default_rng()`?
(We have `GroupsCore.pseudo_rand` and `Oscar.rand_pseudo`, this may be confusing.)

**Comment by kalmarek** [comment]
Thanks for looking into this; 
* Clearly `Oscar.order` should create a new method with `order(::Type{fmpz}, G)` and use it; `GroupsCore` doesn't prohibit you from defining such methods, but it will not force anybody to use `fmpz`, hence `Nemo`. We could also drop the `<:Integer` from `GroupsCore` if it helps anything.
* In general users will expect that `Random.seed!(1)` will work uniformly and the fact that `symmetric_group(3)` is a group defined in GAP seems to be an implementation detail?; there was a discussion about it in Oscar iirc, but I don't remember the conclusions? was it left as a todo, or rather as won't fix?.
* the names `rand_pseudo` and `pseudo_rand` should obviously be united this way or the other. I included it in the interface only due to explicit request, but I'm not sold on this name/functionality (i.e. in which way `rand` is not "pseudo"?!)

**Comment by kalmarek** [comment]
with https://github.com/kalmarek/GroupsCore.jl/pull/25 and https://github.com/oscar-system/Oscar.jl/pull/402 `test_Group_interface(G)` passes.

the next thing is `Base.deepcopy_internal(g::GAPGroupElem, stackdict::IdDict)`.

**Comment by kalmarek** [comment]
so I've added
```julia
function Base.deepcopy_internal(
    g::BasicGAPGroupElem,
    stackdict::IdDict,
)
    return BasicGAPGroupElem(
        parent(g),
        Base.deepcopy_internal(g.X, stackdict),
    )
end
```
to `src/GAPGroups.jl`, but then I get (with `GroupsCore` deved at https://github.com/kalmarek/GroupsCore.jl/tree/enh/group_constructions)
```julia
[...]
Equality, deepcopy && hash: Error During Test at /home/kalmar/.julia/dev/GroupsCore/test/conformance_test.jl:100
  Test threw exception
  Expression: deepcopy(g) == g
  Error thrown by GAP: Error, Panic: basic object of type '<null>' is unkind
  not in any function at *stdin*:1
  
  Stacktrace:
    [1] error(::String, ::String)
      @ Base ./error.jl:42
    [2] error_handler()
      @ GAP ~/.julia/packages/GAP/Gc53G/src/GAP.jl:45
    [3] #invokelatest#2
      @ ./essentials.jl:708 [inlined]
    [4] invokelatest
      @ ./essentials.jl:706 [inlined]
    [5] error_handlerwrap()
      @ GAP ~/.julia/packages/GAP/Gc53G/src/GAP.jl:49
    [6] _call_gap_func(func::GAP_jll.MPtr, a1::GAP_jll.MPtr, a2::GAP_jll.MPtr)
      @ GAP ~/.julia/packages/GAP/Gc53G/src/ccalls.jl:250
    [7] call_gap_func_nokw
      @ ~/.julia/packages/GAP/Gc53G/src/ccalls.jl:204 [inlined]
    [8] (::GAP_jll.MPtr)(a1::GAP_jll.MPtr, a2::GAP_jll.MPtr)
      @ GAP ~/.julia/packages/GAP/Gc53G/src/ccalls.jl:215
    [9] ==(x::GAP_jll.MPtr, y::GAP_jll.MPtr)
      @ GAP ~/.julia/packages/GAP/Gc53G/src/adapter.jl:256
   [10] ==(x::PermGroupElem, y::PermGroupElem)
      @ Oscar ~/.julia/dev/Oscar/src/Groups/GAPGroups.jl:184
   [11] eval_test(evaluated::Expr, quoted::Expr, source::LineNumberNode, negate::Bool)
      @ Test /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:277
   [12] macro expansion
      @ ~/.julia/dev/GroupsCore/test/conformance_test.jl:100 [inlined]
   [13] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [14] macro expansion
      @ ~/.julia/dev/GroupsCore/test/conformance_test.jl:89 [inlined]
   [15] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [16] test_GroupElement_interface(g::PermGroupElem, h::PermGroupElem)
      @ Main ~/.julia/dev/GroupsCore/test/conformance_test.jl:68
julia: src/plist.c:470: KTNumHomPlist: Assertion `!TEST_OBJ_FLAG(elm, TESTING)' failed.

signal (6): Aborted
in expression starting at REPL[9]:1
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
__assert_fail_base.cold at /usr/lib/libc.so.6 (unknown line)
__assert_fail at /usr/lib/libc.so.6 (unknown line)
KTNumHomPlist at /workspace/srcdir/gap/src/plist.c:470 [inlined]
TypePlistHom at /workspace/srcdir/gap/src/plist.c:735
TYPE_OBJ at /workspace/srcdir/gap/src/objects.h:488 [inlined]
TYPE_OBJ_FEO at /workspace/srcdir/gap/src/opers.c:1508 [inlined]
DoOperationNArgs at /workspace/srcdir/gap/src/opers.c:1857 [inlined]
DoOperation1Args at /workspace/srcdir/gap/src/opers.c:1986
ViewObj at /workspace/srcdir/gap/src/objects.c:1078
FuncViewObj at /workspace/srcdir/gap/src/objects.c:1114
CALL_1ARGS at /workspace/srcdir/gap/src/calls.h:320 [inlined]
Call1ArgsInNewReader at /workspace/srcdir/gap/src/read.c:2893
FuncSTREAM_CALL at /home/kalmar/.julia/packages/GAP/Gc53G/pkg/JuliaInterface/src/JuliaInterface.c:334
CALL_3ARGS at /workspace/srcdir/gap/src/calls.h:330 [inlined]
EvalOrExecCall at /workspace/srcdir/gap/src/funcs.c:170 [inlined]
ExecProccall3args at /workspace/srcdir/gap/src/funcs.c:228
EXEC_STAT at /workspace/srcdir/gap/src/stats.c:52 [inlined]
ExecSeqStatHelper at /workspace/srcdir/gap/src/stats.c:148 [inlined]
ExecSeqStat6 at /workspace/srcdir/gap/src/stats.c:187
EXEC_STAT at /workspace/srcdir/gap/src/stats.c:52 [inlined]
EXEC_CURR_FUNC at /workspace/srcdir/gap/src/stats.c:58
DoExecFunc at /workspace/srcdir/gap/src/funcs.c:483 [inlined]
DoExecFunc1args at /workspace/srcdir/gap/src/funcs.c:505
_call_gap_func at /home/kalmar/.julia/packages/GAP/Gc53G/src/ccalls.jl:237
call_gap_func_nokw at /home/kalmar/.julia/packages/GAP/Gc53G/src/ccalls.jl:204 [inlined]
MPtr at /home/kalmar/.julia/packages/GAP/Gc53G/src/ccalls.jl:214
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
show at /home/kalmar/.julia/dev/Oscar/src/Groups/GAPGroups.jl:206
show_delim_array at ./show.jl:1124
show_delim_array at ./show.jl:1109 [inlined]
show at ./show.jl:1142 [inlined]
show_unquoted at ./show.jl:1187 [inlined]
show_unquoted at ./show.jl:1188
unknown function (ip: 0x7f85ea676c55)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
show_list at ./show.jl:1435
show_list at ./show.jl:1416 [inlined]
show_unquoted at ./show.jl:1857
show_unquoted at ./show.jl:1657 [inlined]
print at ./show.jl:1183
unknown function (ip: 0x7f85ea65efb5)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#13 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:314
unknown function (ip: 0x7f85ea65ec8f)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#sprint#385 at ./strings/io.jl:105
sprint at ./strings/io.jl:101 [inlined]
eval_test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:312
macro expansion at /home/kalmar/.julia/dev/GroupsCore/test/conformance_test.jl:119 [inlined]
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
macro expansion at /home/kalmar/.julia/dev/GroupsCore/test/conformance_test.jl:115 [inlined]
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
test_GroupElement_interface at /home/kalmar/.julia/dev/GroupsCore/test/conformance_test.jl:68
unknown function (ip: 0x7f85ea65dfdc)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
#run_repl#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#874 at ./client.jl:387
jfptr_YY.874_46600.clone_1 at /home/kalmar/packages/julias/julia-1.6/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:714
#invokelatest#2 at ./essentials.jl:708 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
run_main_repl at ./client.jl:372
exec_options at ./client.jl:302
_start at ./client.jl:485
jfptr__start_41020.clone_1 at /home/kalmar/packages/julias/julia-1.6/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at julia (unknown line)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x4007d8)
Allocations: 33270725 (Pool: 33231722; Big: 39003); GC: 13
[1]    2515150 abort (core dumped)  julia --project

```
@fingolfin @ThomasBreuer

**Comment by ThomasBreuer** [comment]
Sorry, I cannot reproduce this GAP error.

But I get failures. I think we cannot expect `deepcopy` to return a new object in the case of immutable types.
``` 
julia> g = symmetric_group(3)
Sym( [ 1 .. 3 ] )

julia> x = gens(g)[1]
(1,2,3)

julia> deepcopy(x) === x
true

julia> deepcopy(x.X) === x.X
true

julia> isbits(x)
false
```
Note that GAP permutations are regarded as not copyable.

**Comment by kalmarek** [comment]
```julia
using Pkg
pkg"dev Oscar"
pkg"add GroupsCore#enh/group_constructions"
using Test, Oscar, GroupsCore

function Base.deepcopy_internal(
    g::Oscar.BasicGAPGroupElem,
    stackdict::IdDict,
)
    return Oscar.BasicGAPGroupElem(
        parent(g),
        Base.deepcopy_internal(g.X, stackdict),
    )
end

G = symmetric_group(3)
g, h = gap_perm([2,1,3]), gap_perm([2,3,1])
include(joinpath(dirname(pathof(GroupsCore)), "..", "test", "conformance_test.jl"))
test_GroupElement_interface(g,h)
```
crashes repeatedly here ;/

**Comment by kalmarek** [comment]
and this:
```julia
julia> G = symmetric_group(3)
Sym( [ 1 .. 3 ] )

julia> g, h = gap_perm([2,1,3]), gap_perm([2,3,1])
((1,2), (1,2,3))

julia> deepcopy(g)
[  ]

julia> deepcopy(g) === g
false

julia> deepcopy(g), g
(Error showing value of type Tuple{PermGroupElem, PermGroupElem}:
ERROR: Error thrown by GAP: Error, Log2Int: <n> must be an integer (not a integer) in
  Log2Int( a ) at /home/kalmar/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/cyclotom.g:1001 called from 
String( n ) at /home/kalmar/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/integer.gi:1775 called from
ViewString( obj ) at /home/kalmar/.julia/artifacts/8dd2012d4ef66568b7667a066059847825d8a1f2/share/gap/lib/object.gi:421 called from
<function "ViewObj default method trying ViewString">( <arguments> )
 called from read-eval loop at *stdin*:1
```
this is with `GAP-0.5.2` have I broken something in my installation?

**Comment by ThomasBreuer** [comment]
With the released GAP.jl v0.5.2, I can reproduce crashes, due to the missing `deepcopy_internal` method. (This is available in the dev branch of GAP.jl, but that was clear.)

With the dev branch of GAP.jl, I get two errors due to missing `parent_type` methods (they will be added with the pull request oscar-system/Oscar.jl/pull/409) and three failures due to `deepcopy` returning its argument (mentioned in my previous comment).

**Comment by kalmarek** [comment]
@ThomasBreuer well then I don't understand the semantics of `deepcopy` of GAP objects. Can you create two distinguishable copies of `(1,2,3)`, or are all of them uniformly equal?

Where are the failures with deepcopy exactly happening?

**Comment by kalmarek** [comment]
@fingolfin, @ThomasBreuer did you try to push it forward?

We started this as a base for Oscar, so it would be a shame not to use it given all the discussions that sunk in, so if you have plans to incorporate it in Oscar (probably as lightweight dependency to AA), please let me know. 

Otherwise, I'll further simplify the interface and move forward with mutable API. But I need a decision here.

**Comment by fingolfin** [comment]
Agreed. I still want to use it. Let me get back to you early next week. I need to work on some other stuff right now

**Comment by fingolfin** [comment]
So I discussed with @ThomasBreuer and in principle I'd really like to move forward with this.

But we do have a serious problem with two may package dependencies. My favorite model (as I explained before) would be to not have a GroupsCore package, but instead make this part of AbstractAlgebra -- simply because AbstractAlgebra is already a dependency, and it seems to fit in there nicely. 

If this would be an option for you, then I would immediately move forward with this and get this into AA, then convert the Oscar code to use it (once AA is released). (And then move some of the documentation we've been working on to this code here, propose some further additions, etc.)

However, if you strongly prefer to have GroupsCore as a separate entity, this is a much harder sell. I'll need to have a pow-wow with @fieker @thofma @ThomasBreuer and others (say on Friday after our weekly call on gather.town, which usually lasts from 15:00-15:20 or 15:30 -- you (Marek) can join, too, if you like; if the time is really bad for you, we can try to arrange a separate time, but the above mentioned is probably the easiest to get all on the table soon)

**Comment by kalmarek** [comment]
I made `AA` as dependency of `GroupsCore` (`GC` for short) only to enable easy testing (i.e. to extend methods). Since `AA` doesn't implement any functions related to groups, there is no point in adding it as a dependency, isn't it?

At the moment `GC` has just three deps: `Random` (for implementing `rand`, etc), `Markdown` (docs) and `AA` which is used in the following way:
```julia
import AbstractAlgebra
import AbstractAlgebra: elem_type, gens, ngens, order, parent_type
import AbstractAlgebra: inv!, mul!
const Group = AbstractAlgebra.Group
const GroupElement = AbstractAlgebra.GroupElem
```

If `AA` were to depend on `GC`, a similar (mirrored) 5 lines would need to appear in `AA` (see below).

Note that 
* `elem_type` defaults to `eltype` for groups, so it could become `AA` internal thing;
* The same goes to `parent_type`, which (after converting several implementations of groups to the API) I never used. 
* `inv!` is "implemented" only by `Perm`s, and the method only pretends to do it in-place, so this function should be probably removed from `AA`. 

To summarize, potential changes to `AA` will be as follows:
1. depend on `GC`,
2. add 
```julia
import GroupsCore
import GroupsCore: gens, ngens, order
import GroupsCore: mul!
const Group = GroupsCore.Group
const GroupElem = GroupsCore.GroupElement

elem_type(T::Type{<:Group}) = eltype(T)
```
3. incorporate `test/symmetric.jl` into `AA/src/Generic/PermGroups.jl`.
4. `Groups` are no longer `Set`s ;) (They probably should become `Monoid`s, but that's for another time.)  Subtyping `Group <: Set` as of https://github.com/Nemocas/AbstractAlgebra.jl/blob/efd291f659ba6dedf33b2243bf8faa76ea999e14/src/AbstractTypes.jl#L12 doesn't make sense from pragmatic perspective (do `Groups` in `AA` or `Oscar` want to implement any methods of `Set`s?).  It is also incorrect from julia perspective (`Set` become concrete before or at 1.0 and there is `AbstractSet` above it). Luckily it went unnoticed, so we can change it without any repercussions ;).

----
Given the minimal changes and how well `GC` integrates into `AA` the issue boils down to the question if `AA` devs are willing to accept `GC` as fairly minimal dependency. Friday afternoon is not a great fit for me, but I can try this week (if my sh...y internet permits ;)

ps. any ideas why `AA.mul!` is this not extending `LinearAlgebra.mul!`? I was under the impression that `AA` matrices are not subtype of `AbstractMatrix` so it won't cause any clashes.

**Comment by fingolfin** [comment]
Actually, another appointment cropped up for me which means I have to leave tomorrow around 15:30 -- so maybe next week is better for all (any times particularly good/bad for you?)

Regarding `Set` vs `Monoid` vs `Group`: I feel there is a major design discussion hidden there (yes every group can considered as a monoid, or perhaps even a set; but strictly speaking that is applying a forgetful functor, and as we learned in GAP, doing this can lead to subtle or not so subtle problems, namely when certain properties have different meanings in different categories (e.g.: if G is a group, then every set of monoid generators of G is also a set of group generators, but not vice versa). This, plus the fact that Julia doesn't support multiple inheritance, not even in a limited form as Java does (which is the one thing about Java I always found sensible), means that I am being relatively sceptical about trying to use Julia types to model mathematical hierarchies such these (Group/Monoid/Semigroup/Magma/Set... or Ring/Semiring/... etc.)

**Comment by kalmarek** [comment]
Indeed, I agree; This is the reason why change no 4. should be a no-stopper ;) Maybe defining 
* `gens(G::Group) = gens(typeof(G), G)`
* `gens(::Type{<:Group}, G::Group) # generators of a group and 
* `gens(::Type{<:Monoid}, G::Group)` #generators of a monoid
would make it, but this is a discussion for a different time. 

My time is pretty busy:
Monday: after 3pm;
Tuesday: no
Wednesday: free
Thursday: no
Friday: maybe morning (before 11:00) 

How about Monday 3pm?

**Comment by fieker** [comment]
On Thu, Jun 24, 2021 at 11:11:41AM -0700, Marek Kaluba wrote:
> Indeed, I agree; This is the reason why change no 4. should be a no-stopper ;) Maybe defining 
> * `gens(G::Group) = gens(typeof(G), G)`
> * `gens(::Type{<:Group}, G::Group) # generators of a group and 
> * `gens(::Type{<:Monoid}, G::Group)` #generators of a monoid
> would make it, but this is a discussion for a different time. 
> 
As all types here are abstract, the signature are ambigous for all
concrete group types. I suspect that
gens(::Type{Group}, G::Group)
would work though

so gens(Group, G) -> gens as a group
   gens(Monoid, G) as a moniod
but
   gens(GrpPerm, G) would be ambigous in the original proposal.

We use this idea already
  cyclotomic_field(n) -> AnticNumberField
  cyclotomic_field(ClassField, n) -> ClassField
  cyclotomic_field(NonSimpleNumField, n) a sparse version

Other problem as groups come in many flavours: what type is returned for
gens(Monoid, G) where G is a perm group? Elements of sub-type of MonoidElem or
GroupElem? The parent?

**Comment by kalmarek** [comment]
These are great insights, but outside of scope of the main discussion here, I'm afraid

**Comment by ThomasBreuer** [comment]
Concerning the question

> Other problem as groups come in many flavours: what type is returned for
> gens(Monoid, G) where G is a perm group? Elements of sub-type of MonoidElem or
> GroupElem? The parent?

I do not catch the point:
If the question is to get monoid generators of a group then the result should be an array of group elements with this property. If the aim is to create generating monoid elements (in order to use them in some function for monoids) then I would first construct a monoid isomorphic with the given group (its elements have the right type), and then apply `gens` to it.

**Comment by fingolfin** [comment]
Sorry, this slipped past me again (Monday 3pm wouldn't have worked for me anyway, though)... So let's see if we can pin something down: for me, best days/times are:  Tuesday/Wednesday/Friday 12:30 - 17:00. Other days/times are possible but I have to carefully arrange to make sure I don't have a baby sitting on my lap at the same time 😂 . Based on what @kalmarek writes, this suggests Wednesday afternoon. Unfortunately, that's today, so (a) a bit short notice and (b) we have guests today (fully vaccinated and tested ;-) ). So it's another delay, but we could do it next week, finally???

**Comment by kalmarek** [comment]
@fingolfin, don't worry I already had something on my schedule by yesterday. Next Monday afternoon? Next Wednesday?

**Comment by fingolfin** [comment]
Next Wednesday, 14:00 in gather.town?
