### ISSUE TITLE
Conformance test without random API

### ISSUE THREAD

**Issue by blegat** [kalmarek/GroupsCore.jl#44]
It would be useful to be able to run the conformance tests for a group that does not implement the GroupsCore API. Maybe by using the generators ? Or Maybe by combining the generators randomly ?

**Comment by lgoettgens** [comment]
I think it's easier if I answer here. My colleague @felix-roehrich implemented generalized Weyl groups in Oscar here.
We definitely agree that adding a proper rand function is very painful in our case. Thus, our implementation of rand does not provide real uniform randomness. I am very much in favor of removing the need of a rand function for the API.

One further note: Removing the need of a custom rand function shouldn't be a breaking change.

**Comment by kalmarek** [comment]
to quote @fingolfin from here: https://github.com/oscar-system/Oscar.jl/pull/3070#issuecomment-1841865387

> Indeed: I don't really see any benefit from having GroupsCore, only drawbacks.

I'm glad that you finally found the courage to be more open about it ;)
We will then take `GroupsCore` in its own direction without worrying about `Oscar`.
