### ISSUE TITLE
Additative groups

### ISSUE THREAD

**Issue by albinahlback** [kalmarek/GroupsCore.jl#6]
I suppose that additative groups is alias for commutative groups. Since AA implements this abstract type, I think we should as well.

**Comment by kalmarek** [comment]
I don't think we're going to support additive groups. In GAP there is a very limited support for those (aka teaching mode), but nothing beyond that. If you want to work with some of these it should be essentially trivial (that's the goal of this interface) to wrap multiplicative group around it. E.g.
```julia
struct AdditiveGroupElem{GEl}
    g::GEl
end

Base.:*(a::AGEl, b::AGEl) where AGEl <: AdditiveGroupElement = AGEl(a.g+b.g)
Base.inv(a::AGEl) where AGEl<:AdditiveGroupElement = AGEl(-a.g)
GroupsCore.isabelian(::AdditiveGroupElement) = true
# ... [+ lean implementation of Group interface]
```
??

**Comment by albinahlback** [comment]
Yes, sounds good. Didn't think it through, but when you are saying it like that, it sound like a better alternative to just implement `isabelian`.
