### ISSUE TITLE
equality for groups

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/GroupsCore.jl#9]
* Option 1: we "implement" only `===` and `isisomorphic`; `==` throws an error.
* Option 2: what `==` should mean?

**Comment by ThomasBreuer** [comment]
In GAP, equality of groups, rings, etc. means equality as sets. That is, two groups G, H are regarded as equal if G is a subset of H and H is a subset of G.
The question for equality in this sense is often useful, for example when a function returns some group and you want to know whether you have already dealt with this group: Fetch two random elements of a given group G and count how often they generate the whole group G or a prescribed subgroup of G; the "most natural" way to formulate this condition is in terms of equality.

On the other hand, equality as sets is not always the right concept. Think of a finite field with p^2 elements. It can be viewed as a vector space over itself or over the field with p elements, and these two vector spaces are equal as sets.
(Perhaps polynomial rings with different monomial orderings are an even more striking example.)

I think that trying to define an equality of algebraic structures that requests also certain structural properties to be equal would be asking for trouble. The main concern is that either one cannot extend the definition such that some new properties must be respected, or one cannot guarantee backwards compatibility.
(Consider two functions f1 and f2 that return a group, and the results in a given example are equal. Then a new structural property gets added to the list of properties that have to be equal if two groups shall be regarded as equal; one could think about the field of definition of a matrix group, or a bilinear form that is respected, or the array or set of generators. Both f1 and f2 do not know about this change, and perhaps the code called by the functions has different opinions what this new structural property shall be for the group object that gets constructed somewhere. Thus the results of f1 and f2 in the given example can suddenly be regarded as not equal.)

I think that questions for equality of two algebraic structures (with different meanings, according to the context) are natural, but that the equality operator is not the right function to formulate such questions. Perhaps introducing `isequal_as_set` (and analogous functions as needed) would be a better choice.

**Comment by kalmarek** [comment]
@ThomasBreuer do I read it correctly as a supportive argument for the first option?

**Comment by ThomasBreuer** [comment]
@kalmarek Yes, I vote for `==` not being defined for algebraic structures like groups, because of its ambiguity.

**Comment by thofma** [comment]
Or `==` defaults to `===`? I am thinking mainly of parent checks here. So one could write `parent(g) == parent(h)` instead of `parent(g) === parent(h)`. One also has to be careful because of the `Dict` interface. I always forget if it wants `==` or `isequal` to play nice with `hash`.

**Comment by kalmarek** [comment]
as of now the decision was taken not to implement `==` for Groups. `hash` is not implemented as well and we treat parent objects as (local) singletons
